### PR TITLE
Add synctex option to choose pane

### PR DESCRIPTION
**Pull request by sherwoodinc**
This would implement what I proposed in #159. 

I added the relevant option and the code using it.
The "default" setting kees the current behavior.

### CODE REVIEW

**Comment by izuzak** [comment]
Thanks for opening a pull request for this, @sherwoodinc ⚡️ 

Unfortunately, I no longer have synctex installed on my machine so can't test this out. Could you perhaps record a GIF which demonstrates how this works and post it here? So, a GIF which shows how the behavior for opening the file changes as you modify the value of the `paneToUseInSynctex` config setting? 🙏 The code looks good to me, but just want to make sure it's doing what we expect it should. 😸 Thanks!

**Comment by sherwoodinc** [comment]
Of course!
I added 4 pane options (left, right, top, bottom) which are the 4 possible options for the workspace.open(...) atom API method, and "default" which uses the current pane (and keeps the old behavior).
I will record a GIF and post it.

**Comment by sherwoodinc** [comment]
Screencast
peek 2016-12-21 17-01

**Comment by izuzak** [comment]
Great! Thanks!

**Pull request merged**
