### PR TITLE
SyncTeX support

### PR DESCRIPTION
**Pull request by autc04**
SyncTeX support is now ready for review.

### CODE REVIEW

**Comment by izuzak** [comment]
:zap: @autc04 :zap: 

Just tried this out and works great -- thanks so much for adding this. I did notice one small problem, however -- when I click on a line in the PDF, the .tex file for that PDF is opened correctly, but the cursor is positioned on the line _following_ the one it should be positioned on (i.e. if I clicked on line N, cursor is positioned on N+1). Any chance there's an off-by-one error somewhere (or a difference in how lines are indexed, 1-based vs 0-based)? Are you seeing the same or do you see correct behavior?

**Comment by autc04** [comment]
Indeed. The fact that a text editor that would inflict 1-based column numbers on me in the UI would use 0-based line numbers in the API caught me off guard.

**Comment by izuzak** [comment]
:sparkling_heart: Just published a new version with this -- thanks again!

**Comment by olmokramer** [comment]
Amazing work @autc04! Thank you very much! :)

**Pull request merged**
